name: Testing fosit_ecommerce_store

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v2
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run black check
      run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v2
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run flake8 check
      run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v2
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run mypy check
      run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    services:

      fosit_ecommerce_store-db:
        image: bitnami/mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: "fosit_ecommerce_store"
          MYSQL_ROOT_USER: "fosit_ecommerce_store"
          MYSQL_DATABASE: "fosit_ecommerce_store"
          MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
        options: --health-cmd="mysqladmin ping -u root" --health-interval=15s --health-timeout=5s --health-retries=6
        ports:
        - 3306:3306
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v2
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="fosit_ecommerce_store" .
      env:
        FOSIT_ECOMMERCE_STORE_HOST: "0.0.0.0"
        FOSIT_ECOMMERCE_STORE_DB_HOST: localhost
